trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  EmployeeDataFile: './Data/employees.json' # Path to employees.json file

steps:
# Step 1: Cache NuGet Packages
- task: Cache@2
  displayName: 'Cache NuGet Packages'
  inputs:
    key: 'nuget | "$(Agent.OS)" | $(Build.SourcesDirectory)/nuget.config'
    restoreKeys: |
      nuget | "$(Agent.OS)"
    path: $(NUGET_PACKAGES)

# Step 2: Install NuGet (If Needed)
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet Tool'

# Step 3: Restore NuGet Packages
- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    restoreSolution: '$(solution)'

# Step 4: Build Solution
- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Step 5: Run Tests
- task: VSTest@2
  displayName: 'Run Unit Tests'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Step 6: Read and Display Employee Data File
- script: |
    if [ -f "$(EmployeeDataFile)" ]; then
      echo "Contents of Employee Data File:"
      cat "$(EmployeeDataFile)" | jq
    else
      echo "File not found: $(EmployeeDataFile)"
    fi
  displayName: 'Display Employee Data File'
