trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'Release'
  EmployeeDataFile: './Data/employees.json'

steps:
# Step 1: Cache NuGet Packages
- task: Cache@2
  displayName: 'Cache NuGet Packages'
  inputs:
    key: 'nuget | "$(Agent.OS)" | EmployeeFunctionApp.sln'
    restoreKeys: |
      nuget | "$(Agent.OS)"
    path: $(NUGET_PACKAGES)

# Step 2: Cache .NET SDK Installation
- task: Cache@2
  displayName: 'Cache .NET SDK'
  inputs:
    key: 'dotnet | "$(Agent.OS)"'
    restoreKeys: |
      dotnet | "$(Agent.OS)"
    path: $(DOTNET_INSTALL_DIR)

# Step 3: Checkout Repository
- task: Checkout@1
  displayName: 'Checkout GitHub Repository'

# Step 4: Debug Variables (Optional for Troubleshooting)
- script: |
    echo "Build.SourcesDirectory = $(Build.SourcesDirectory)"
    echo "EmployeeDataFile = $(EmployeeDataFile)"
  displayName: 'Debug Variables'

# Step 5: Display Employee Data File
- script: |
    if [ -f "$(EmployeeDataFile)" ]; then
      echo "Contents of Employee Data File:"
      cat "$(EmployeeDataFile)"
    else
      echo "File not found: $(EmployeeDataFile)"
    fi
  displayName: 'Display Employee Data File'

# Step 6: Restore NuGet Packages
- script: |
    dotnet restore EmployeeFunctionApp.sln
  displayName: 'Restore NuGet Packages'

# Step 7: Build Solution
- script: |
    dotnet build EmployeeFunctionApp.sln --configuration $(BuildConfiguration)
  displayName: 'Build Solution'

# Step 8: Run Unit Tests
- script: |
    dotnet test EmployeeFunctionApp.sln --configuration $(BuildConfiguration) --no-build
  displayName: 'Run Unit Tests'
