trigger:
  branches:
    include:
      - main # Triggers pipeline 

pool:
  vmImage: 'windows-latest' 

variables:
  BuildConfiguration: 'Release' # Build config (Debug or Release)

steps:
# Step 1: Install .NET SDK
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    version: '9.0' 
    includePreviewVersions: true

# Step 2: Restore NuGet Packages
- script: |
    dotnet restore EmployeeFunctionApp.sln
  displayName: 'Restore NuGet Packages'

# Step 3: Build Solution
- script: |
    dotnet build EmployeeFunctionApp.sln --configuration $(BuildConfiguration)
  displayName: 'Build Solution'

# Step 4: Run Unit Tests
- script: |
    dotnet test EmployeeFunctionApp.sln --configuration $(BuildConfiguration) --no-build
  displayName: 'Run Unit Tests'


